#!/bin/bash

## This script is run periodically to determine if the container is "healthy".
## To return HEALTHY (0), crond must be running and the defined ${NEXTCLOUD_CONTAINER} must be accessible and running.

## Import common variables and functions.
source /.ncbu_lib

## Exit codes
HEALTHY=0
UNHEALTHY=1

printf "%b" "$(TIMESTAMP_f) - Initiating healthcheck... "

## Ensure crond is running:
if ! pgrep crond > /dev/null; then
    printf "%b" "Healthcheck failed - crond not running.\n"
    exit ${UNHEALTHY};
fi

## Ensure the defined nextcloud app container is still present and running:
if [ $(docker inspect --format '{{.State.Running}}' ${NEXTCLOUD_CONTAINER}) != "true" ]; then
    printf "%b" "Healthcheck failed - missing nextcloud container.\n"
    exit ${UNHEALTHY};
fi

## Everything seems okay.
printf "%b" "Healthcheck passed.\n"
exit ${HEALTHY}
