#!/bin/bash

## This script is run periodically to determine if the container is "healthy".
## To return HEALTHY (0), crond must be running and the defined $NEXTCLOUD_CONTAINER must be accessible and running.

## Exit codes
HEALTHY=0
UNHEALTHY=1

## Text formatting for stdout.
BOLD="\033[01;37m"
RESET="\033[0m"

## Function to print current date and time.
TIMESTAMP_f () { date +%Y-%m-%d\ %T; }

printf "%b" "${BOLD}$(TIMESTAMP_f)${RESET} - Initiating healthcheck...\n"

# Ensure crond is running:
if ! pgrep crond; then
    printf "%b" "${BOLD}$(TIMESTAMP_f)${RESET} - Healthcheck failed - crond not running.\n" | tee -a ${LOGFILE}
    exit ${UNHEALTHY};
fi

# Ensure the defined nextcloud app container is still present and running:
if [ $(docker inspect --format '{{.State.Running}}' ${NEXTCLOUD_CONTAINER}) != "true" ]; then
    printf "%b" "${BOLD}$(TIMESTAMP_f)${RESET} - Healthcheck failed - missing nextcloud container.\n" | tee -a ${LOGFILE}
    exit ${UNHEALTHY};
fi

# Everything seems okay.
printf "%b" "${BOLD}$(TIMESTAMP_f)${RESET} - Healthcheck passed.\n" | tee -a ${LOGFILE}
exit ${HEALTHY}
